# Generated by Django 3.0.3 on 2020-02-29 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from app.models import get_upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('potSize', models.IntegerField()),
                ('lastPotted', models.DateTimeField()),
                ('nextPot', models.DateTimeField()),
                ('lastFert', models.DateTimeField()),
                ('parentID', models.IntegerField()),
                ('otherParentID', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=get_upload_path)),
                ('dateTaken', models.DateTimeField(auto_now_add=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('coleusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Coleus')),
            ],
        ),
        migrations.AddField(
            model_name='coleus',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Variety'),
        ),
    ]
