# Generated by Django 3.0.4 on 2020-04-03 23:22

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('booked', models.BooleanField(default=False)),
                ('background', models.BooleanField(default=False)),
                ('allDay', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('start', models.DateTimeField(null='true')),
                ('end', models.DateTimeField(null='true')),
            ],
        ),
        migrations.CreateModel(
            name='NoteSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('availabilityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Availability')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to=app.models.get_avatar_path)),
                ('isTeacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('availabilityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Availability')),
                ('learnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerID', to=settings.AUTH_USER_MODEL)),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachesSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('teacherID', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteSetSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NoteSet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='NoteSetContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to=app.models.get_upload_path)),
                ('noteSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NoteSet')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('dateSent', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.FileField(null=True, upload_to=app.models.get_chat_upload_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
                ('sentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='them', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('otherUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherPerson', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personWhoOwnsIt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
