# Generated by Django 3.0.4 on 2020-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
