# Generated by Django 3.0.3 on 2020-03-06 20:24

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteSetContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to=app.models.get_upload_path)),
                ('noteSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NoteSet')),
            ],
        ),
        migrations.CreateModel(
            name='NoteSetSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NoteSet')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VideoService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('content', models.FileField(upload_to=app.models.get_upload_path)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoServiceSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('videoServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VideoService')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='coleusID',
        ),
        migrations.DeleteModel(
            name='Coleus',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
        migrations.AddField(
            model_name='notesetsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
        migrations.AddField(
            model_name='noteset',
            name='videoServiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VideoService'),
        ),
    ]
