# Generated by Django 3.0.4 on 2020-04-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutoringsession_isconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='booked',
        ),
    ]
