# Generated by Django 3.0.3 on 2020-04-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='classSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='studentsTaking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='LessonSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availID', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='app.Availability')),
                ('subject', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
        ),
    ]
