# Generated by Django 3.0.3 on 2020-03-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200306_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteset',
            old_name='userID',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='videoservice',
            old_name='userID',
            new_name='owner',
        ),
    ]
