# Generated by Django 3.0.3 on 2020-03-07 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20200307_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoservice',
            name='content',
        ),
        migrations.AddField(
            model_name='videoservice',
            name='dateScheduled',
            field=models.DateTimeField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='videoservice',
            name='duration',
            field=models.DurationField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='videoservice',
            name='repeatDays',
            field=models.CharField(max_length=100, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='videoservice',
            name='repeatFrequency',
            field=models.CharField(max_length=100, null='true'),
            preserve_default='true',
        ),
        migrations.CreateModel(
            name='UserAttendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateScheduled', models.DateTimeField(null='true')),
                ('duration', models.DurationField(null='true')),
                ('learnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_session_set', to=settings.AUTH_USER_MODEL)),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_session_set', to=settings.AUTH_USER_MODEL)),
                ('videoServiceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VideoService')),
            ],
        ),
    ]
