# Generated by Django 3.0.3 on 2020-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200307_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null='true'),
            preserve_default='true',
        ),
    ]
