# Generated by Django 3.0.3 on 2020-03-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200310_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='dateScheduled',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='availability',
            name='start',
            field=models.DateTimeField(null='true'),
            preserve_default='true',
        ),
    ]
