# Generated by Django 3.0.3 on 2020-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200311_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
