# Generated by Django 3.0.3 on 2020-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200311_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='repeatDays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='repeatFrequency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
