# Generated by Django 3.0.3 on 2020-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200311_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='description',
        ),
        migrations.AddField(
            model_name='availability',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='background',
            field=models.BooleanField(default=False),
        ),
    ]
