# Generated by Django 3.0.3 on 2020-03-13 04:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200311_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='repeatDays',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='repeatFrequency',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_avatar_path),
        ),
    ]
