# Generated by Django 3.0.3 on 2020-04-02 15:26

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20200313_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('dateSent', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.FileField(upload_to=app.models.get_chat_upload_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
                ('sentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='them', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('otherUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherPerson', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personWhoOwnsIt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
