# Generated by Django 3.0.3 on 2020-04-03 18:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_chat_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='picture',
            field=models.FileField(null=True, upload_to=app.models.get_chat_upload_path),
        ),
    ]
